[package]
name = "check_if_email_exists"
version = "0.4.0"
authors = ["Amaury Martiny <amaury.martiny@protonmail.com>"]
categories = ["email"]
description = "Check if an email address exists without sending any email"
documentation = "http://docs.rs/check_if_email_exists"
edition = "2018"
keywords = ["email", "smtp", "mx", "email verification"]
licence = "GPL-3.0"
publish = true
repository = "https://github.com/amaurymartiny/check_if_email_exists"
readme = "../README.md"

[badges]
appveyor = { repository = "https://github.com/amaurymartiny/check_if_email_exists", service = "github" }
travis-ci = { repository = "https://github.com/amaurymartiny/check_if_email_exists", service = "github" }

[dependencies]
lettre = "0.9"
log = "0.4"
mailchecker = "3.3"
native-tls = "^0.2"
rand = "0.7"
rayon = "1.2.0"
trust-dns-resolver = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
